apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: weekend-k8s-lab
  labels:
    app: mongo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: lab
  MONGO_INITDB_ROOT_PASSWORD: lab-dev-only
  MONGO_INITDB_DATABASE: weekend
