apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: registry
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: registry-storage
  hostPath:
    path: /srv/k8s-lab/registry
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-node1
